export const ERROR = {
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  PAGINATION_ERROR: "PAGINATION_ERROR",

  COURSE_PROMPT: "COURSE_PROMPT",
  COURSE_ID: "COURSE_ID",
  COURSE_NOT_FOUND: "COURSE_NOT_FOUND",
  COURSE_VIOLATION: "COURSE_VIOLATION",

  MODULE_ID: "MODULE_ID",
  MODULE_NOT_FOUND: "MODULE_NOT_FOUND",
  MODULE_VIOLATION: "MODULE_VIOLATION",

  LESSON_ID: "LESSON_ID",
  LESSON_NOT_FOUND: "LESSON_NOT_FOUND",
  LESSON_VIOLATION: "LESSON_VIOLATION",

  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_EMAIL_EXISTS: "USER_EMAIL_EXISTS",
  USER_EMAIL_NOT_FOUND: "USER_EMAIL_NOT_FOUND",
  USER_PASSWORD_NOT_MATCH: "USER_PASSWORD_NOT_MATCH",
  USER_ACCOUNT_INACTIVE: "USER_ACCOUNT_INACTIVE",
  USER_ROLE_NOT_FOUND: "USER_ROLE_NOT_FOUND",

  REGISTER_VALIDATION: "REGISTER_VALIDATION",
  LOGIN_VALIDATION: "LOGIN_VALIDATION",
  AUTHORIZATION_CODE_MISSING: "AUTHORIZATION_CODE_MISSING",

  TOKEN_NOT_FOUND: "TOKEN_NOT_FOUND",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",

  REFRESH_TOKEN_NOT_FOUND: "REFRESH_TOKEN_NOT_FOUND",
  REFRESH_TOKEN_INVALID: "REFRESH_TOKEN_INVALID",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",

  AVATAR_REQUIRED: "AVATAR_REQUIRED",
  ONLY_IMAGES_ALLOWED: "ONLY_IMAGES_ALLOWED",
};
